import enum


class ListActions(enum.Enum):
    START = 'START',
    SEARCH_CATEGORY = 'SEARCH_CATEGORY',
    SEND_MESSAGE_PSYCHOLOGISTS = 'SEND_MESSAGE_PSYCHOLOGISTS',
    CANCEL_SEND_MESSAGE_PSYCHOLOGISTS = 'CANCEL_SEND_MESSAGE_PSYCHOLOGISTS',
    GET_ALL_UNALLOCATED_MESSAGES_FOR_PSYCHOLOGISTS = 'GET_ALL_UNALLOCATED_MESSAGES_FOR_PSYCHOLOGISTS',
    GET_ALL_PSYCHOLOGISTS = 'GET_ALL_PSYCHOLOGISTS',
    GET_TEN_RESPONSIBLE_MESSAGES_FOR_PSYCHOLOGISTS = 'GET_TEN_RESPONSIBLE_MESSAGES_FOR_PSYCHOLOGISTS',
    GET_ARCHIVE_MESSAGE_PSYCHOLOGIST = 'GET_ARCHIVE_MESSAGE_PSYCHOLOGIST',
    DELETE_USER_MESSAGE_FOR_PSYCHOLOGISTS = 'DELETE_USER_MESSAGE_FOR_PSYCHOLOGISTS',
    ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY',
    ANSWER_QUESTION_FROM_CATEGORY = 'ANSWER_QUESTION_FROM_CATEGORY',
    SEARCH_OTHER_CATEGORIES = 'SEARCH_OTHER_CATEGORIES',
    PSYCHOLOGIST_RESPONSIBLE = 'PSYCHOLOGIST_RESPONSIBLE',
