import enum


class ListActions(enum.Enum):
    START = 'START',
    GET_ALL_UNALLOCATED_MESSAGES_FOR_PSYCHOLOGISTS = 'GET_ALL_UNALLOCATED_MESSAGES_FOR_PSYCHOLOGISTS',
    GET_ALL_PSYCHOLOGISTS = 'GET_ALL_PSYCHOLOGISTS',
    GET_TEN_RESPONSIBLE_MESSAGES_FOR_PSYCHOLOGISTS = 'GET_TEN_RESPONSIBLE_MESSAGES_FOR_PSYCHOLOGISTS',
    GET_ARCHIVE_MESSAGE_PSYCHOLOGIST = 'GET_ARCHIVE_MESSAGE_PSYCHOLOGIST',
    GET_ANSWER_QUESTION_FROM_CATEGORY = 'GET_ANSWER_QUESTION_FROM_CATEGORY',
    # GET_ALL_USERS = 'GET_ALL_USERS',
    SEARCH_CATEGORY = 'SEARCH_CATEGORY',
    SET_USERS_IS_PSYCHOLOGISTS = 'SET_USERS_IS_PSYCHOLOGISTS',
    SET_PSYCHOLOGIST_RESPONSIBLE = 'SET_PSYCHOLOGIST_RESPONSIBLE',
    SEND_MESSAGE_PSYCHOLOGISTS = 'SEND_MESSAGE_PSYCHOLOGISTS',
    CANCEL_SEND_MESSAGE_PSYCHOLOGISTS = 'CANCEL_SEND_MESSAGE_PSYCHOLOGISTS',
    DELETE_USER_MESSAGE_FOR_PSYCHOLOGISTS = 'DELETE_USER_MESSAGE_FOR_PSYCHOLOGISTS',
    ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY',
