export enum ListActions {
  START = 'START',
  BEGIN = 'BEGIN',
  SEND_MESSAGE_PSYCHOLOGY = 'SEND_MESSAGE_PSYCHOLOGY',
  ALL_COMMANDS_PSYCHOLOGY = 'ALL_COMMANDS_PSYCHOLOGY',
  GET_ALL_MESSAGES_PSYCHOLOGY = 'GET_ALL_MESSAGES_PSYCHOLOGY',
  DELETE_MESSAGE_PSYCHOLOGY = 'DELETE_MESSAGE_PSYCHOLOGY',
  CANCEL_MESSAGE_PSYCHOLOGY = 'CANCEL_MESSAGE_PSYCHOLOGY',
  //Category
  CTG_FAMILY = 'CTG_FAMILY',
  CTG_FAMILY_PARENTS = 'CTG_FAMILY_PARENTS',
  CTG_FAMILY_BROTHER_SISTER = 'CTG_FAMILY_BROTHER_SISTER',
  CTG_SCHOOL = 'CTG_SCHOOL',
  CTG_SCHOOL_BULLYING = 'CTG_SCHOOL_BULLYING',
  CTG_FRIENDS = 'CTG_FRIENDS',
}
